### ISSUE TITLE
Cilk: stack mmap fails on WSL Linux (due to unsupported mmap operation using MAP_GROWSDOWN flag)

### ISSUE THREAD

**Issue by jsukha** [OpenCilk/cheetah#7]
Minor issue, but just wanted to report this in case anyone else runs into similar problems.    
I am unable to initialize the runtime when building/running using WSL (WIndows Subsystem for Linux).
Functional workaround seems to be to remove MAP_GROWSDOWN from the flags to mmap.   I did not attempt to do any performance testing or any significant correctness tests however.

Details:  

Basic programs (fib) fail with errno code 95, which is an unsupported operation, at the following line that calls mmap.

https://github.com/OpenCilk/cheetah/blob/832aeeb95f122ba2324e7e739f60fce3171ff342/runtime/fiber.c#L210

The MAP_GROWSDOWN flag seems to be unsupported on my test machine.    
Building OpenCilk using WSL2 with Linux version  Ubuntu 20.04.3 LTS.   (Windows 10 build, 19043.1466)

I couldn't find any obvious documentation to indicate whether this is expected behavior for WSL Linux or not, so it might be a gap in the WSL implementation?   TBD.

**Comment by neboat** [comment]
I just used OpenCilk to build and run some Cilk code on WLS2 a couple days ago, without any issue.  I'm on the same version of Ubuntu, and my Windows 10 build is slightly newer (19044), but I doubt that's the problem.  I'm not quite sure what the issue might be.

**Comment by jsukha** [comment]
Hm, fascinating....  I tried this on a second Windows machine (Windows 10 build 19044.1466).  It works just fine on this one.

The main difference I can think of is the second machine is an 11th generation i5 with 32 GB of RAM, but the first one is a 6th generation i5 with 4 GB of RAM.    Setting CILK_STACKSIZE to 16384 doesn't change any behavior on the first machine either...

Perhaps there is some machine or platform-specific branching in the mmap implementation?  Maybe it's something else entirely.   At some point I can probably create a short reproducer example using mmap and file a bug report on the WSL forum..

**Comment by VoxSciurorum** [comment]
My understanding is WLS2 supports both a library implementation of Linux and a hypervisor that can run a Linux kernel.  Is it possible that your problematic build was using the first environment?

**Comment by jsukha** [comment]
Hm, possibly?  This was a while ago, and this was an older laptop that I had to retire already.     I think at the time, that machine was also too slow to reasonably build LLVM anyway, so I gave up on it and forgot about this post.    I'll close this for now.

**Comment by jsukha** [comment]
Changing reason to "can't reproduce".
